In [37]:
import pandas as pd
import numpy as np

In [52]:
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report


In [39]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/zoo/zoo.data",names=['name','hair','feathers','eggs','milk','airborne','aquatic','predator','toothed','backbone','breathes','venomous','fins','legs','tail','domestic','catsize','type'])

In [40]:
df

name  hair  feathers  eggs  milk  airborne  aquatic  predator  \
0    aardvark     1         0     0     1         0        0         1   
1    antelope     1         0     0     1         0        0         0   
2        bass     0         0     1     0         0        1         1   
3        bear     1         0     0     1         0        0         1   
4        boar     1         0     0     1         0        0         1   
..        ...   ...       ...   ...   ...       ...      ...       ...   
96    wallaby     1         0     0     1         0        0         0   
97       wasp     1         0     1     0         1        0         0   
98       wolf     1         0     0     1         0        0         1   
99       worm     0         0     1     0         0        0         0   
100      wren     0         1     1     0         1        0         0   

     toothed  backbone  breathes  venomous  fins  legs  tail  domestic  \
0          1         1         1         0     0     4     0         0   
1          1         1         1         0     0     4     1         0   
2          1         1         0         0     1     0     1         0   
3          1         1         1         0     0     4     0         0   
4          1         1         1         0     0     4     1         0   
..       ...       ...       ...       ...   ...   ...   ...       ...   
96         1         1         1         0     0     2     1         0   
97         0         0         1         1     0     6     0         0   
98         1         1         1         0     0     4     1         0   
99         0         0         1         0     0     0     0         0   
100        0         1         1         0     0     2     1         0   

     catsize  type  
0          1     1  
1          1     1  
2          0     4  
3          1     1  
4          1     1  
..       ...   ...  
96         1     1  
97         0     6  
98         1     1  
99         0     7  
100        0     2  

[101 rows x 18 columns]

In [53]:
y=df['type']
print(y)

0      1
1      1
2      4
3      1
4      1
      ..
96     1
97     6
98     1
99     7
100    2
Name: type, Length: 101, dtype: int64


In [54]:
x.shape


(101, 17)

In [66]:
del x['name']

In [67]:
x

hair  feathers  eggs  milk  airborne  aquatic  predator  toothed  \
0       1         0     0     1         0        0         1        1   
1       1         0     0     1         0        0         0        1   
2       0         0     1     0         0        1         1        1   
3       1         0     0     1         0        0         1        1   
4       1         0     0     1         0        0         1        1   
..    ...       ...   ...   ...       ...      ...       ...      ...   
96      1         0     0     1         0        0         0        1   
97      1         0     1     0         1        0         0        0   
98      1         0     0     1         0        0         1        1   
99      0         0     1     0         0        0         0        0   
100     0         1     1     0         1        0         0        0   

     backbone  breathes  venomous  fins  legs  tail  domestic  catsize  
0           1         1         0     0     4     0         0        1  
1           1         1         0     0     4     1         0        1  
2           1         0         0     1     0     1         0        0  
3           1         1         0     0     4     0         0        1  
4           1         1         0     0     4     1         0        1  
..        ...       ...       ...   ...   ...   ...       ...      ...  
96          1         1         0     0     2     1         0        1  
97          0         1         1     0     6     0         0        0  
98          1         1         0     0     4     1         0        1  
99          0         1         0     0     0     0         0        0  
100         1         1         0     0     2     1         0        0  

[101 rows x 16 columns]

In [82]:
X_train, x_test, Y_train, y_test = train_test_split(x,y,
                                                 test_size = 0.4,train_size=0.6,
                                                 random_state = 42)

In [83]:

clf = DecisionTreeClassifier()

In [84]:
clf

DecisionTreeClassifier()

In [85]:
clf = clf.fit(X_train,Y_train)

In [86]:
y_pred = clf.predict(x_test)

In [87]:
print("Confusion Matrix: ",
        confusion_matrix(y_test, y_pred))
      
    

Confusion Matrix:  [[20  0  0  0  0  0  0]
 [ 0  5  0  0  0  0  0]
 [ 0  0  1  0  1  0  0]
 [ 0  0  0  2  0  0  0]
 [ 0  0  0  0  2  0  0]
 [ 0  0  0  0  0  5  0]
 [ 0  0  0  0  0  1  4]]


In [88]:
print ("Accuracy : ",
    accuracy_score(y_test,y_pred)*100)
   

Accuracy :  95.1219512195122


In [89]:
print("Report : ",
    classification_report(y_test, y_pred))

Report :                precision    recall  f1-score   support

           1       1.00      1.00      1.00        20
           2       1.00      1.00      1.00         5
           3       1.00      0.50      0.67         2
           4       1.00      1.00      1.00         2
           5       0.67      1.00      0.80         2
           6       0.83      1.00      0.91         5
           7       1.00      0.80      0.89         5

    accuracy                           0.95        41
   macro avg       0.93      0.90      0.89        41
weighted avg       0.96      0.95      0.95        41

